config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :verybests

      resources :roles

      resources :actors

      resources :directors

      resources :movies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "movies#index"
  resources :verybests
  resources :roles
  resources :actors
  resources :directors
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/verybest.rb
class Verybest < ApplicationRecord
  # Direct associations

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    created_at
  end
end

app/controllers/api/v1/verybests_controller.rb
class Api::V1::VerybestsController < Api::V1::GraphitiController
  def index
    verybests = VerybestResource.all(params)
    respond_with(verybests)
  end

  def show
    verybest = VerybestResource.find(params)
    respond_with(verybest)
  end

  def create
    verybest = VerybestResource.build(params)

    if verybest.save
      render jsonapi: verybest, status: :created
    else
      render jsonapi_errors: verybest
    end
  end

  def update
    verybest = VerybestResource.find(params)

    if verybest.update_attributes
      render jsonapi: verybest
    else
      render jsonapi_errors: verybest
    end
  end

  def destroy
    verybest = VerybestResource.find(params)

    if verybest.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: verybest
    end
  end
end

app/controllers/verybests_controller.rb
class VerybestsController < ApplicationController
  before_action :set_verybest, only: %i[show edit update destroy]

  def index
    @q = Verybest.ransack(params[:q])
    @verybests = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show; end

  def new
    @verybest = Verybest.new
  end

  def edit; end

  def create
    @verybest = Verybest.new(verybest_params)

    if @verybest.save
      redirect_to @verybest, notice: "Verybest was successfully created."
    else
      render :new
    end
  end

  def update
    if @verybest.update(verybest_params)
      redirect_to @verybest, notice: "Verybest was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @verybest.destroy
    redirect_to verybests_url, notice: "Verybest was successfully destroyed."
  end

  private

  def set_verybest
    @verybest = Verybest.find(params[:id])
  end

  def verybest_params
    params.fetch(:verybest, {})
  end
end

app/views/verybests/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Verybest #<%= verybest.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back verybest, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_verybest_url(verybest), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to verybest, method: :delete, data: { confirm: "Do you really want to delete this verybest?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(verybest.updated_at) %> ago
  </div>
</div>

app/views/verybests/_form.html.erb
<% was_validated = verybest.errors.any? %>

<%= form_with(model: verybest, local: true, novalidate: true, class: "mb-3") do |f| %>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/verybests/_list_item.html.erb
<%= link_to verybest, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= verybest %>
    <small class="text-muted">
      <%= time_ago_in_words(verybest.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/verybests/_verybests_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "verybests_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/verybests" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#verybests_filters">
  Show filters
</a>

app/views/verybests/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Verybest #<%= @verybest.id %>
      </h2>

      <div class="card-body">
        <%= render "form", verybest: @verybest %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/verybests/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Verybests

      <%= link_to new_verybest_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "verybests/verybests_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Verybests

        <%= link_to new_verybest_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @verybests, partial: "list_item", as: :verybest %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @verybests, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/verybests/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Verybest
      </h2>

      <div class="card-body">
        <%= render "form", verybest: @verybest %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/verybests/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @verybest, partial: "card", as: :verybest %>
  </div>
</div>